### ISSUE TITLE
Naming convention for ATL15 Antarctica products not compatible with interp_SMB_ICESat2_ATL15.py

### ISSUE THREAD

**Issue by rohaizharis** [tsutterley/SMBcorr#26]
The ATL15 Antarctica product is split into four quadrants and as a result, the regions are labeled as A1,A2,A3 & A4 in the filenames for the products. interp_SMB_ICESat2_ATL15.py requires a certain naming convention for ATL15 input files and expects the region to be labeled "AA" in the filename. If the products are not renamed to match the specified naming convention in the function, the following error is thrown:

```
CRITICAL:root:process id 1483 failed
ERROR:root:Traceback (most recent call last):
  File "/Users/rohaizharis/miniforge3/envs/SMB/lib/python3.12/site-packages/SMBcorr-0.0.0.2-py3.12.egg/EGG-INFO/scripts/interp_SMB_ICESat2_ATL15.py", line 508, in main
    interp_SMB_ICESat2(args.directory, args.infile, args.model,
  File "/Users/rohaizharis/miniforge3/envs/SMB/lib/python3.12/site-packages/SMBcorr-0.0.0.2-py3.12.egg/EGG-INFO/scripts/interp_SMB_ICESat2_ATL15.py", line 158, in interp_SMB_ICESat2
    MODEL, = [key for key,val in models[RGN].items() if model_version in val]
                                 ~~~~~~^^^^^
KeyError: '10km/ATL15_A1'
```

**Comment by tsutterley** [comment]
This is what I get for not touching a code base since ATL15 R002. Should be fixed in #29
