### ISSUE TITLE
KeyError: interp_SMB_ICESat2_ATL15.py hemisphere flag dictionary expects different keys

### ISSUE THREAD

**Issue by rohaizharis** [tsutterley/SMBcorr#33]
In  interp_SMB_ICESat2_ATL15.py, a hemisphere flag ('S' or 'N') is set depending on the region of interest. However in Line 262, the hemisphere flag dictionary is indexed for 'AA' or 'GL' resulting in the following error:

```CRITICAL:root:process id 86182 failed
ERROR:root:Traceback (most recent call last):
  File "/Users/rohaizharis/miniforge3/envs/SMB/lib/python3.12/site-packages/SMBcorr-0.0.0-py3.12.egg/EGG-INFO/scripts/interp_SMB_ICESat2_ATL15.py", line 520, in main
    interp_SMB_ICESat2(args.directory, args.infile, args.model,
  File "/Users/rohaizharis/miniforge3/envs/SMB/lib/python3.12/site-packages/SMBcorr-0.0.0-py3.12.egg/EGG-INFO/scripts/interp_SMB_ICESat2_ATL15.py", line 262, in interp_SMB_ICESat2
    MERRA2_REGION = dict(AA='ais',GL='gris')[HEM]
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'S'```

**Comment by tsutterley** [comment]
should be fixed in #32 :facepalm:
